# Generated by Django 3.0 on 2021-10-30 06:50

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('salary', models.FloatField()),
                ('location', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('a', 'Any')], default='a', max_length=1)),
                ('required_age', models.IntegerField(default=25)),
                ('experience', ckeditor.fields.RichTextField(default='Prior experience is an added advantage.', help_text='Use 600 words', max_length=600)),
                ('description', ckeditor.fields.RichTextField(help_text='Use 600 words only', max_length=600)),
                ('requirements', ckeditor.fields.RichTextField(blank=True, help_text='Use 400 words only.', max_length=400, null=True)),
                ('positions', models.IntegerField(default=1)),
                ('taken', models.BooleanField(default=False)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
            ],
        ),
        migrations.CreateModel(
            name='JobsApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, max_length=100, null=True, verbose_name='Applicant names')),
                ('email', models.EmailField(max_length=225, verbose_name='Applicant email')),
                ('phone', models.CharField(max_length=32, verbose_name='Applicant phone')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('terms', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_job', to='jobs.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='applied_by')),
            ],
        ),
    ]
