# Generated by Django 3.0 on 2021-10-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20211030_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=20, verbose_name='proposed pay'),
        ),
    ]
