# Generated by Django 3.0 on 2021-10-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20211030_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(help_text='use 150 words to describe the the pay', max_length=150, verbose_name='proposed pay'),
        ),
    ]
