# Generated by Django 3.0 on 2021-10-30 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20211030_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobsapplication',
            name='names',
        ),
        migrations.AddField(
            model_name='jobsapplication',
            name='age',
            field=models.IntegerField(default=25, help_text='Minimum required age is 25 years', validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(choices=[('m', 'Male only'), ('f', 'Female only'), ('a', 'Any gender preffered')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='jobsapplication',
            name='phone',
            field=models.CharField(help_text='** Please provide your phone number', max_length=32, verbose_name='Applicant phone'),
        ),
    ]
