# Generated by Django 3.0 on 2021-10-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20211030_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsapplication',
            name='selected',
            field=models.BooleanField(default=False, verbose_name='Selected for interview'),
        ),
        migrations.AlterField(
            model_name='jobsapplication',
            name='phone',
            field=models.CharField(help_text='Fomart (+123 456 789 1234)', max_length=32, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='jobsapplication',
            name='terms',
            field=models.BooleanField(default=True, verbose_name='Accept terms'),
        ),
    ]
