# Generated by Django 3.0 on 2021-10-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20211030_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsapplication',
            name='applied',
            field=models.BooleanField(default=False, verbose_name='Application'),
        ),
    ]
