# Generated by Django 3.0 on 2021-10-30 15:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobsapplication_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Use 2000 words only', max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=ckeditor.fields.RichTextField(default='Prior experience is an added advantage.', help_text='Use 2000 words', max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Use 2000 words only.', max_length=2000, null=True),
        ),
    ]
