# Generated by Django 3.0 on 2021-10-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20211030_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsapplication',
            name='applied',
        ),
    ]
