# Generated by Django 3.0 on 2021-10-31 07:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_jobsapplication_applied'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, editable=False, max_length=250, null=True),
        ),
    ]
