# Generated by Django 3.0 on 2021-11-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='segment',
            field=models.CharField(default='create-job', max_length=10),
        ),
    ]
