# Generated by Django 3.0 on 2021-11-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20211102_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='domain',
            field=models.CharField(default='127.0.0.1:8000', max_length=250),
            preserve_default=False,
        ),
    ]
