# Generated by Django 3.0 on 2021-11-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_avatar',
            field=models.ImageField(default='company.png', upload_to=None),
            preserve_default=False,
        ),
    ]
