# Generated by Django 3.2 on 2021-11-04 17:58

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_job_company_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_avatar',
            field=models.ImageField(upload_to=jobs.models.images_directory_path),
        ),
    ]
