# Generated by Django 3.2 on 2021-11-04 18:04

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_alter_job_company_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_avatar',
            field=models.ImageField(height_field='142', upload_to=jobs.models.images_directory_path, width_field='400'),
        ),
    ]
