# Generated by Django 3.2 on 2021-11-04 18:38

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_alter_job_company_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='no_applications',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_avatar',
            field=models.ImageField(upload_to=jobs.models.images_directory_path),
        ),
    ]
