# Generated by Django 3.0 on 2021-10-29 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/profiles/staff/avatars/')),
                ('gender', models.CharField(choices=[('s', 'Select'), ('m', 'Male'), ('f', 'Female')], default='s', max_length=1)),
                ('phone', models.CharField(blank=True, help_text='Business number for communication', max_length=32, null=True)),
                ('resume', models.TextField(blank=True, help_text='Use 1000 words only. To be pulished in the website.', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InnovestUsersMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, max_length=100, null=True, verbose_name='your_name')),
                ('email', models.EmailField(max_length=225)),
                ('inform_us', models.CharField(help_text='Ask question, Inform us on anything.', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/profiles/employees/avatars/')),
                ('gender', models.CharField(choices=[('s', 'Select'), ('m', 'Male'), ('f', 'Female')], default='s', max_length=1)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.CharField(blank=True, help_text='Include your city or your area.', max_length=50, null=True)),
                ('resume', models.FileField(blank=True, help_text='Attach your resume most prefferably in word formart.', null=True, upload_to='media/profiles/employees/resumes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
