# Generated by Django 3.0 on 2021-10-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeeprofile_innovestusersmessages_staffprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovestusersmessages',
            name='updated_at',
        ),
    ]
