# Generated by Django 3.0 on 2021-10-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_innovestusersmessages_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovestusersmessages',
            name='user',
        ),
        migrations.AddField(
            model_name='innovestusersmessages',
            name='session_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
