# Generated by Django 3.0 on 2021-10-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211029_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovestSubcribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='client email')),
                ('phone', models.EmailField(blank=True, max_length=100, null=True, verbose_name='client phone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='innovestusersmessages',
            name='names',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='client name'),
        ),
    ]
