# Generated by Django 3.0 on 2021-10-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211029_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovestsubcribers',
            name='email',
        ),
        migrations.AlterField(
            model_name='innovestsubcribers',
            name='phone',
            field=models.CharField(default='0000000000', help_text='Phone number is required to be sending text messages for new jobs', max_length=100, verbose_name='client phone'),
            preserve_default=False,
        ),
    ]
