# Generated by Django 3.0 on 2021-10-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211029_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovestsubcribers',
            name='subscribe',
            field=models.CharField(blank=True, default='Innovest subscriber', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='innovestusersmessages',
            name='message',
            field=models.CharField(blank=True, default='Innovest Message', max_length=1000, null=True),
        ),
    ]
