# Generated by Django 3.0 on 2021-10-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211029_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovestsubcribers',
            name='phone',
        ),
        migrations.AddField(
            model_name='innovestsubcribers',
            name='email',
            field=models.EmailField(default='lili@g.com', help_text='Phone number is required to be sending text messages for new jobs', max_length=100, verbose_name='client phone'),
            preserve_default=False,
        ),
    ]
