# Generated by Django 3.0 on 2021-10-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211029_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovestsubcribers',
            name='email',
            field=models.EmailField(help_text='We will be sending you new jobs', max_length=100, verbose_name='Subscriber email'),
        ),
    ]
