# Generated by Django 3.0 on 2021-10-31 09:50

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211030_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, editable=False, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='resume',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Use 1000 words only. To be pulished in the website.', max_length=1000, null=True),
        ),
    ]
