# Generated by Django 3.0 on 2021-11-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_innovestsubcribers_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovestsubcribers',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
