# Generated by Django 3.2 on 2021-11-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211102_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Second name'),
        ),
    ]
