# Generated by Django 3.2 on 2021-11-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20211104_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Second name'),
        ),
    ]
