# Generated by Django 3.2 on 2021-11-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20211104_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='second_name',
        ),
    ]
