# Generated by Django 3.2 on 2021-11-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_themes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themes',
            name='user',
        ),
        migrations.AddField(
            model_name='themes',
            name='session',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='current sesion'),
        ),
    ]
